version: '3.4'

services:
  conferenceattendees.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
   
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  conferenceattendees.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
   
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
